frontend: improve "use max token balance" feature
beamer-bridge/beamer pull request #1150
Opened 2022-10-21 10:40 UTC by GabrielBuragev

Fixes #1127 

I adjusted the `UInt256` abstraction to not support creation of negative integers since that was contradictory to what this class is supposed/expected to do (unsigned should stand for positive only). It was necessary to adjust it as so since i introduced arithmetic operations over it.

Also includes a solution to [Manuel's suggestion](https://github.com/beamer-bridge/beamer/issues/1127#issuecomment-1278048533)

2022-10-21 13:17 UTC, compojoom commented on frontend/tests/unit/services/transactions/request-manager.spec.ts
> +        expect(baseAmount.format(DECIMALS)).toBeCloseTo(decimalResult, DECIMALS - 1);
I would actually convert the decimal amount to wei using ethersjs and then make sure that the expected wei amounts match

2022-10-21 13:18 UTC, compojoom commented on frontend/tests/unit/services/transactions/request-manager.spec.ts
> +        expect(baseAmount.format(DECIMALS)).toBeCloseTo(decimalResult, DECIMALS - 1);
same as above.

2022-10-21 13:20 UTC, compojoom commented on frontend/src/services/transactions/request-manager.ts
> +export async function deriveBaseTransferableAmountFromTotalAmount(
maybe: getAmountBeforeFees(totalAmountWei...)

2022-10-21 13:25 UTC, compojoom requested changes
Just the few changes as we discussed in the call.

2022-10-24 07:34 UTC, GabrielBuragev commented on frontend/src/services/transactions/request-manager.ts
> +export async function deriveBaseTransferableAmountFromTotalAmount(
:heavy_check_mark:

2022-10-24 07:46 UTC, GabrielBuragev commented
> I would actually convert the decimal amount to wei using ethersjs and then make sure that the expected wei amounts match

So, for this part, i solved it by [writing my own function](https://github.com/beamer-bridge/beamer/pull/1150/commits/7b93024202fa3542a1248854e8746a95a213c899#diff-80b936d3f9979a9815e5987d0f4e5e45a775ffffdedbbbc1a03f09c99f321dc9R31-R39) that transforms the decimal number to wei since using ethersjs in the tests leads to:
- Undesirable extra dependency 
- `"fractional component exceeds decimals"` error when trying to parse a JS floating number with `N` decimals to a Wei representation with `N-M` (M > 0) decimals. IOW, we have to pass this function a JS floating number with exact same decimals that we are trying to represent the Wei amount to. That will almost never be possible since JS cannot be restricted to using `N` number of decimals when doing division. 
We could use JS `floatNumber.toFixed(decimalCount)` but that leads to another undesired behavior which is rounding the decimals.

Considering all of the above, i decided to write a simple but limited function to do the job for our specific test cases.

2022-10-25 13:28 UTC, compojoom approved these changes
LGTM

2022-10-25 14:06 UTC, GabrielBuragev commented
Update on the final implementation:
We decided to simplify the tests by checking the response from the function against static values (expected results) instead of having the decimal calculation logic inside the tests.

2022-10-25 14:08 UTC, merged