Stakes to be uint96
beamer-bridge/beamer pull request #1245
Opened 2022-12-02 16:01 UTC by fredo

use uint96 for stakes so that we can access claim states with less read operations

2022-12-10 17:30 UTC, istankovic commented
> use uint96 for stakes so that we can access claim states with less read operations

Are you sure this is really the case?

From a cursory comparison of the generated optimised IR of
```
struct Claim1 {                                          
    uint96 x;                                            
}                                                        
                                                         
struct Claim2 {                                          
    uint256 y;                                           
}                                                        
                                                         
contract Foo {                                           
    mapping (uint256 => Claim1) claims1;                 
    mapping (uint256 => Claim2) claims2;                 
                                                         
   function bar(uint256 i) public returns (uint96) {     
        uint96 b = claims1[i].x;                         
        return b;                                        
    }                                                    
                                                         
    function baz(uint256 i) public returns (uint256) {   
        uint256 z = claims2[i].y;                        
        return z;                                        
    }                                                    
```

I can see that it is in fact the `uint96` version that does more work:
```
function shift_right_0_unsigned(value) -> newValue                                                                         
{ newValue := shr(0, value) }                                                                                              
function cleanup_from_storage_t_uint96(value) -> cleaned                                                                   
{                                                                                                                          
    cleaned := and(value, 0xffffffffffffffffffffffff)                                                                      
}                                                                                                                          
function extract_from_storage_value_offset_0t_uint96(slot_value) -> value                                                  
{                                                                                                                          
    value := cleanup_from_storage_t_uint96(shift_right_0_unsigned(slot_value))                                             
}                                                                                                                          
function read_from_storage_split_offset_0_t_uint96(slot) -> value                                                          
{                                                                                                                          
    value := extract_from_storage_value_offset_0t_uint96(sload(slot))                                                      
}                                                                                                                          
/// @ast-id 33 @src 0:168:274  "function bar(uint256 i) public returns (uint96) {..."                                      
function fun_bar_33(var_i_18) -> var__21                                                                                   
{                                                                                                                          
    /// @src 0:208:214  "uint96"                                                                                           
    let zero_t_uint96_1 := zero_value_for_split_t_uint96()                                                                 
    var__21 := zero_t_uint96_1                                                                                             
    /// @src 0:237:244  "claims1"                                                                                          
    let _2_slot := 0x00                                                                                                    
    let expr_25_slot := _2_slot                                                                                            
    /// @src 0:245:246  "i"                                                                                                
    let _3 := var_i_18                                                                                                     
    let expr_26 := _3                                                                                                      
    /// @src 0:237:247  "claims1[i]"                                                                                       
    let _4 := mapping_index_access_t_mapping$_t_uint256_$_t_struct$_Claim1_$3_storage_$_of_t_uint256(expr_25_slot, expr_26)
    let _5_slot := _4                                                                                                      
    let expr_27_slot := _5_slot                                                                                            
    /// @src 0:237:249  "claims1[i].x"                                                                                     
    let _6 := add(expr_27_slot, 0)                                                                                         
    let _7 := read_from_storage_split_offset_0_t_uint96(_6)                                                                
    let expr_28 := _7                                                                                                      
    /// @src 0:226:249  "uint96 b = claims1[i].x"                                                                          
    let var_b_24 := expr_28                                                                                                
    /// @src 0:266:267  "b"                                                                                                
    let _8 := var_b_24                                                                                                     
    let expr_30 := _8                                                                                                      
    /// @src 0:259:267  "return b"                                                                                         
    var__21 := expr_30                                                                                                     
    leave                                                                                                                  
}                                                                                                                          
/// @src 0:67:477  "contract Foo {..."                                                                                     
```

Compare this to
```
function cleanup_from_storage_t_uint256(value) -> cleaned                                                                   
{ cleaned := value }                                                                                                        
function extract_from_storage_value_offset_0t_uint256(slot_value) -> value                                                  
{                                                                                                                           
    value := cleanup_from_storage_t_uint256(shift_right_0_unsigned(slot_value))                                             
}                                                                                                                           
function read_from_storage_split_offset_0_t_uint256(slot) -> value                                                          
{                                                                                                                           
    value := extract_from_storage [...]

2022-12-12 08:46 UTC, fredo commented
Thanks for taking the effort for this test! 

Unfortunately, your test is not representable for what the PR is trying to achieve.

Let me try to give more clarity here:

### A better representative example

Your example stores only one value per struct. Per default, Solidity's store slot size ist 256 bits. So any value of a struct will be stored in at least 256 bits slots. Looking at your example, it is clear why uint96 creates more work. Both values are stored in a 256 bit slot but the uint96 value has to be masked.

However, Solidity tries to be smart and pack values into one storage slot if possible. So if there were more attributes than one in your structs AND those values can be packed together into one slot, this would be the correct representation for a test.
Example:

```
struct Claim1 {                                          
    uint96 x;
    address y;                                            
} 
```
```
struct Claim2 {                                          
    uint256 x;
    address y;                                            
} 
```

Note that address takes 160 bits, so Claim1 should be possible to be stored in one 256 bits slot whereas in Claim 2, two 256 bits slots would be needed.

`sload` reads 256 bits slots, so the idea behind the change is that one sload (with maybe some additional masking work) can read two parameters of the struct (x and y).

### The actual desired optimization
It is also worth mentioning the actual desired optimization. As described in #1170, in `challengeClaim()` `lastChallenger` is always updated (results in a `SSTORE` operation) even if it is the same value as before. Explicitly this happens, when the same agent counter challenges an ongoing challenge (he was the `lastChallenger` and is it now again). 
In order to conditionally update lastChallenger, we have to read the value first (`SREAD`) and than compare it to the new value (as you can see in the PR).
The reason for trying to squeeze stakes and addresses together into one slot is that we now don't need an additional `SREAD`operation, because `lastChallenger`and `challengerStakesTotal` is now stored in the same slot and we have to read `challengerStakesTotal` anyway. We basically get the read "for free".

### Uint96(msg.value)
This is pretty safe, as there are 120 million ETH in existence which can be stored already in a uint88. If I remember correctly with uint96 we can represent 79e18 ETH which is ~10 orders of magnitude greater than the total number of ETH in existence. It is principally impossible to reach this boundary.


As all of this was a suggestion by the audit company and I did a theoretical research on this to approve, I'd appreciate if you redo the test with a more representative example and have in mind what the original goal of the test is. Also the measure of interest is gas cost (not only number of instructions)

If you have any further questions please reread the issue or just ask me. I'm curious to see what you will find out.

2022-12-13 11:25 UTC, istankovic requested changes
Per our discussion, we decided to do the change, but not in order to reduce the number of read operations (current solc does not do that optimization), rather to reduce the `Claim` storage requirements.

Please also make sure to update the commit message to reflect the new reasoning behind the change.

2022-12-13 11:25 UTC, istankovic commented on contracts/contracts/RequestManager.sol
> +        address lastChallenger = claim.lastChallenger;
We should remove this read of `lastChallenger`.

2022-12-13 11:25 UTC, istankovic commented on contracts/contracts/RequestManager.sol
> +            }
We should remove this `if` and update the `lastChallenger` unconditionally, as before.

2022-12-14 08:48 UTC, fredo commented
I guess #1267 has to be merged first?

2022-12-14 10:12 UTC, GabrielBuragev commented
#1267 is merged 👍

2022-12-14 10:14 UTC, istankovic commented
@fredo could you also please update the commit message?

2022-12-14 10:16 UTC, istankovic approved these changes
Looks good!

2022-12-14 10:58 UTC, merged