frontend: Integrate Safe
beamer-bridge/beamer pull request #1755
Opened 2023-04-27 11:45 UTC by manuelwedler

see #1507
(we still need to open an issue against there repo to get listed in the Safe App)

This was much more work than expected. Some function declarations and interfaces of our internal architecture needed to get changed. A few things are still missing: The warning if the target address is the same as the Safe's one is missing. Some tests are missing. Maybe it would be nicer to use a flag on the `IEthereumProvider` interface if the disconnect should be shown or if the target address should be prefilled.

2023-05-03 11:04 UTC, manuelwedler commented
Added a commit for showing the warning if the same address as the connected Safe is chosen for the target address.

2023-05-03 18:30 UTC, GabrielBuragev requested changes
Nice! Some amazing improvements in the structure of the providers and i can already see its paying off. Great job man.

I have a decent amount of nitpicky suggestions and some questions. Once they are addressed happily approving!

2023-05-08 11:55 UTC, manuelwedler commented on frontend/src/services/web3-provider/safe-provider.ts
> +    console.error('shit');
lol whoops

2023-05-08 12:49 UTC, manuelwedler commented on frontend/src/components/RequestSourceInputs.vue
> +    if (provider.value.switchChainSafely) {
Do you mean a getter on the store that would check if `switchChainSafely` is available on the provider? So the function would still be optional on the `IEthereumProvider` interface. In this case, I think Typescript would still make the `if (provider.value.switchChainSafely)` check required as the typing cannot be inferred from the store getter.

2023-05-08 12:55 UTC, manuelwedler commented on frontend/src/components/RequestSourceInputs.vue
> +    if (provider.value.switchChainSafely) {
The flags I meant should be implemented on the interface and don't relate to the existence of a function on the provider.

2023-05-08 13:13 UTC, manuelwedler commented on frontend/src/services/transactions/request-manager.ts
> +    if (provider.getActualTransactionHash) {
Yeah I think it is nice to have optional methods on the provider interface that allow to modify behavior in some places.

2023-05-08 13:15 UTC, manuelwedler commented on frontend/tests/unit/services/web3-provider/safe-provider.spec.ts
> +      sdk.safe.getInfo = new Promise(function () {});
Cool, thanks!

2023-05-08 14:31 UTC, manuelwedler commented on frontend/src/services/transactions/request-manager.ts
> +  provider: IEthereumProvider,
Sure!

2023-05-08 14:48 UTC, GabrielBuragev commented on frontend/src/components/RequestSourceInputs.vue
> +    if (provider.value.switchChainSafely) {
Ignoring this as discussed. Will not provide much benefit.

2023-05-08 15:48 UTC, merged