Beamer 1745/improve code reuse
beamer-bridge/beamer pull request #1760
Opened 2023-04-28 09:40 UTC by bilbeyt

Close: #1745

2023-04-28 14:23 UTC, istankovic commented on beamer/tests/agent/unit/test_handlers.py
> +ERC2O_ABI = get_ERC20_abi()
Now that we load the ERC20 abi just once, we can remove this global and instead just call `get_ERC20_abi`.

2023-04-28 14:25 UTC, istankovic commented on beamer/agent/chain.py
> +_ERC20_ABI = get_ERC20_abi()
We can get rid of this global now and instead just call `get_ERC20_abi` where needed.

2023-04-28 14:42 UTC, istankovic commented
We should also move `contracts_for_web3` from `scripts/_util.py` to `beamer.contracts`.

2023-04-28 14:51 UTC, istankovic commented
```
>>> import beamer.agent.relayer as r
>>> r.get_relayer_executable()
PosixPath('XXX/beamer/beamer/agent/data/relayers/relayer-node18-linux-x64')
```

This function returns an incorrect path to the relayer.

2023-04-28 14:52 UTC, istankovic requested changes
Overall pretty good, but there are few things to be fixed.

2023-04-28 15:03 UTC, bilbeyt commented
> ```
> >>> import beamer.agent.relayer as r
> >>> r.get_relayer_executable()
> PosixPath('XXX/beamer/beamer/agent/data/relayers/relayer-node18-linux-x64')
> ```
> 
> This function returns an incorrect path to the relayer. I wonder how this got past our CI. Do you have an idea?

paid special attention but still missed this good catch :)

2023-04-28 15:07 UTC, istankovic commented
> paid special attention but still missed this good catch :)

What is concerning is that the CI did not catch it.
I think we should not fix this until we get the CI to fail first because of this.
(That could require writing a new test, or fixing an existing one, if there is one.)

2023-04-28 15:32 UTC, istankovic commented
The Makefile needs updating, we copy relayer binaries to the old location.

2023-05-02 09:14 UTC, istankovic approved these changes
Good work!

2023-05-02 09:15 UTC, merged