frontend: Update transfer success tweet text for Polygon release
beamer-bridge/beamer pull request #2045
Opened 2023-07-12 09:57 UTC by manuelwedler

See #1684

Should only be merged shortly before we go live on Polygon.

2023-07-12 15:04 UTC, manuelwedler commented
Yes, already implemented it on top of your PR. Will updated this PR once the other is merged

2023-07-12 17:07 UTC, manuelwedler commented
Now this is ready for review.

hint: I removed the `ExtendedTransferData` because it was applied to `TransferData` objects and potentially made a `feeSubAddress` available which does not exist. I think using type guards is the safer approach.

2023-07-13 09:50 UTC, GabrielBuragev approved these changes
Thanks for implementing the type guards. Indeed, this is the proper way to do the checks against the different types of transfers.

One small nitpick only.

2023-07-13 09:50 UTC, GabrielBuragev commented on frontend/src/components/ShareTweet.vue
> +    text = defaultText;
Nitpick: We can simply write `return defaultText;` and `return subsidizedTransferText;` here.

2023-07-13 09:51 UTC, GabrielBuragev requested changes
I just noticed this while testing: https://github.com/beamer-bridge/beamer/issues/1684#issuecomment-1633908079

2023-07-13 12:14 UTC, GabrielBuragev approved these changes
Looks perfect now.

2023-07-13 12:56 UTC, merged